[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oblivia_contracts = "8JCmxZrdwiUki2Vr1UbS5LoevXSNpPwohxUCKndopcZG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
