[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
oblivia_contracts = "HaRpXyybfpYpwxkhfj8CjY8EjGqvRd96Zi33iSCTxvHG"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/oblivia-devnet.json"

[scripts]
test = "cargo test"

[hooks]
